


public class Principal extends javax.swing.JFrame {
    private final ListaOrd lista = new ListaOrd();
    private final Queue filaI = new Queue();
    private final Queue filaF = new Queue();
    private final Queue filaM = new Queue();    
    int controle = 0;
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttLMulheres = new javax.swing.JButton();
        bttLHomens = new javax.swing.JButton();
        bttLTodos = new javax.swing.JButton();
        bttMembros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        bttRegistrar = new javax.swing.JButton();
        bttLIdosos = new javax.swing.JButton();
        bttAtender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttLMulheres.setText("Listar Mulheres");
        bttLMulheres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLMulheresActionPerformed(evt);
            }
        });

        bttLHomens.setText("Listar Homens");
        bttLHomens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLHomensActionPerformed(evt);
            }
        });

        bttLTodos.setText("Listar Todos");
        bttLTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLTodosActionPerformed(evt);
            }
        });

        bttMembros.setText("Membros Do Grupo");
        bttMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMembrosActionPerformed(evt);
            }
        });

        txtaArea.setColumns(20);
        txtaArea.setRows(5);
        jScrollPane1.setViewportView(txtaArea);

        jLabel1.setText("Nome: ");

        jLabel2.setText("Idade: ");

        jLabel3.setText("Sexo: ");

        bttRegistrar.setText("Registrar");
        bttRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegistrarActionPerformed(evt);
            }
        });

        bttLIdosos.setText("Listar Idosos");
        bttLIdosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLIdososActionPerformed(evt);
            }
        });

        bttAtender.setText("Atender");
        bttAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAtenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(9, 9, 9)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(txtIdade))))
                        .addGap(18, 18, 18)
                        .addComponent(bttRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttAtender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttLIdosos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bttMembros)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bttLMulheres)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bttLHomens)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bttLTodos)))
                            .addComponent(jScrollPane1))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttMembros)
                            .addComponent(bttRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttLIdosos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLMulheres, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLHomens, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttLMulheresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLMulheresActionPerformed

        if(!filaF.isEmpty()){
            txtaArea.setText("Alunos mulheres cadastrados: \n" + filaF.toString());
        }
        else{
            txtaArea.setText("Sem alunos mulheres cadastrados");
        }
    }//GEN-LAST:event_bttLMulheresActionPerformed

    private void bttLHomensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLHomensActionPerformed
        if(!filaM.isEmpty()){
            txtaArea.setText("Alunos homens cadastrados: \n" + filaM.toString());
        }
        else{
            txtaArea.setText("Sem alunos homens cadastrados");
        }
    }//GEN-LAST:event_bttLHomensActionPerformed

    private void bttLTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLTodosActionPerformed
        if(!lista.isEmpty()){
            txtaArea.setText("Alunos cadastrados: \n" + lista.toString2());
        }
        else{
            txtaArea.setText("Sem alunos cadastrados");
        }
    }//GEN-LAST:event_bttLTodosActionPerformed

    private void bttRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegistrarActionPerformed

        String nome = txtNome.getText();
        int idade = Integer.parseInt(txtIdade.getText());
        char sexo = (txtSexo.getText().charAt(0));
        Pessoa natacao = new Pessoa(nome, idade, sexo);
        if(natacao.getSexo() == 'f' || natacao.getSexo() == 'F' || natacao.getSexo() == 'm' || natacao.getSexo() == 'M'){
            lista.insert(natacao.toString());
        }
        else{
            txtaArea.setText("Sexo Inválido, aluno não adicionado \n");
        }

        int i = 60;
        if(natacao.getIdade() >= i){
            filaI.enqueue(natacao);
            txtaArea.setText("Aluno adicionado com sucesso na lista de idosos \n");
        }
        if(natacao.getSexo() == 'f' && natacao.getIdade() < i){
            filaF.enqueue(natacao);
            txtaArea.setText("Aluno adicionado com sucesso na lista de mulheres \n");
        }
        if(natacao.getSexo() == 'm' && natacao.getIdade() < i){
            filaM.enqueue(natacao);
            txtaArea.setText("Aluno adicionado com sucesso na lista de homens \n");
        }
        if(natacao.getSexo() == 'F' && natacao.getIdade() < i){
            filaF.enqueue(natacao);
            txtaArea.setText("Aluno adicionado com sucesso na lista de mulheres \n");
        }
        if(natacao.getSexo() == 'M' && natacao.getIdade() < i){
            filaM.enqueue(natacao);
            txtaArea.setText("Aluno adicionado com sucesso na lista de homens \n");
        }
        txtNome.setText("");
        txtIdade.setText("");
        txtSexo.setText("");
    }//GEN-LAST:event_bttRegistrarActionPerformed

    private void bttLIdososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLIdososActionPerformed
        if(!filaI.isEmpty()){
            txtaArea.setText("Alunos idosos cadastrados: \n" + filaI.toString());
        }
        else{
            txtaArea.setText("Sem alunos idosos cadastrados");
        }
    }//GEN-LAST:event_bttLIdososActionPerformed

    private void bttAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAtenderActionPerformed
        if(filaI.isEmpty() && filaF.isEmpty() && filaM.isEmpty()){
            txtaArea.setText("Sem alunos cadastrados");
        }
        else{
            if(!filaI.isEmpty()){
                Pessoa i = (Pessoa)filaI.dequeue();
                txtaArea.setText("Em Atendimento: \n" + i.toString());
                controle = (filaF.isEmpty()? 0 : 1);
            }
            else if(!filaF.isEmpty() && controle == 0){
                Pessoa f= (Pessoa)filaF.dequeue();
                txtaArea.setText("Em Atendimento: \n" + f.toString());
                controle = (filaM.isEmpty()? 0 : 1);
            }
            else if(!filaM.isEmpty() && controle == 1){
                Pessoa m = (Pessoa)filaM.dequeue();
                txtaArea.setText("Em Atendimento: \n" + m.toString());
                controle = 0;
            }
        }
    }//GEN-LAST:event_bttAtenderActionPerformed

    private void bttMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMembrosActionPerformed
        txtaArea.setText("Nome: Gustavo Fonseca de Souza, RGM: 20858710" +
                "\n" + "Nome: Gabriel de Jesus Fernandes, RGM: 20552416" +
                "\n" + "Nome: Danilo C da Silva , RGM: 21001171" +
                "\n" + "Nome: Eduardo Araujo de Melo, RGM: 20953275" +
                "\n" + "Nome: Allan Santiago Oshima, RGM: 22195947");
    }//GEN-LAST:event_bttMembrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAtender;
    private javax.swing.JButton bttLHomens;
    private javax.swing.JButton bttLIdosos;
    private javax.swing.JButton bttLMulheres;
    private javax.swing.JButton bttLTodos;
    private javax.swing.JButton bttMembros;
    private javax.swing.JButton bttRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextArea txtaArea;
    // End of variables declaration//GEN-END:variables
}
